datasource:
  url: jdbc:postgresql://localhost:5432/clever
  username: postgres
  password: penelopacristal
  driver: org.postgresql.Driver

liquibase:
  changelog: db/changelog/master.yaml

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
